# -*- coding: utf-8 -*-
"""lowest_cost_first.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pGzbOMZOe8OUdqCC0gw-jx9mimZyqdvF
"""

"""
CSCE 5210 - Fundamentals of Artificial Intelligence
Programming Assignment 1

Name: Mohammed Momin Khizar Uddin
Algorithm: Lowest-Cost-First Search
Problem: Acyclic Delivery Robot Domain from Example 3.6
"""

import heapq
from itertools import count


# Directed acyclic graph from Figure 3.3.
# Each tuple contains: (neighbor, arc cost)
GRAPH = {
    "A": [("B", 1), ("C", 3), ("D", 4)],
    "B": [("E", 2), ("F", 3)],
    "C": [("J", 7)],
    "D": [("H", 4)],
    "E": [],
    "F": [("D", 1)],
    "G": [],
    "H": [("G", 3)],
    "J": [("G", 4)]
}


def lowest_cost_first_search(graph, start, goal):
    """
    Finds a minimum-cost path from the start node to the goal node
    using Lowest-Cost-First Search.
    """

    # This counter is used to break ties between paths having
    # the same accumulated cost.
    tie_breaker = count()

    # Each frontier entry contains:
    # (accumulated cost, tie-breaking number, current node, path)
    frontier = [(0, next(tie_breaker), start, [start])]

    # Stores the lowest known cost of reaching each node.
    best_cost = {start: 0}

    # Records the order in which nodes are expanded.
    expansion_order = []

    print("Lowest-Cost-First Search")
    print(f"Start node: {start}")
    print(f"Goal node:  {goal}")
    print()

    while frontier:
        path_cost, _, current_node, path = heapq.heappop(frontier)

        # Ignore this entry if a cheaper path to the same node
        # has already been discovered.
        if path_cost != best_cost.get(current_node):
            continue

        expansion_order.append(current_node)

        print(
            f"Expanding {current_node} | "
            f"cost = {path_cost:2d} | "
            f"path = {' -> '.join(path)}"
        )

        # Because the frontier is ordered by accumulated cost,
        # the first goal removed from it has minimum cost.
        if current_node == goal:
            return path, path_cost, expansion_order

        # Generate the outgoing neighbors of the current node.
        for neighbor, arc_cost in graph.get(current_node, []):
            new_cost = path_cost + arc_cost

            # Add the path if it gives a lower cost for the neighbor.
            if new_cost < best_cost.get(neighbor, float("inf")):
                best_cost[neighbor] = new_cost

                heapq.heappush(
                    frontier,
                    (
                        new_cost,
                        next(tie_breaker),
                        neighbor,
                        path + [neighbor]
                    )
                )

    # This is returned if the goal cannot be reached.
    return None, float("inf"), expansion_order


def main():
    start_node = "A"
    goal_node = "G"

    path, total_cost, expanded_nodes = lowest_cost_first_search(
        GRAPH,
        start_node,
        goal_node
    )

    print()
    print("Search completed.")
    print("Expansion order:", " -> ".join(expanded_nodes))

    if path is None:
        print("No path exists from the start node to the goal node.")
    else:
        print("Optimal path:   ", " -> ".join(path))
        print("Total cost:     ", total_cost)


if __name__ == "__main__":
    main()